
builders:
  fasq_serializer_generator:
    import: "package:fasq_serializer_generator/fasq_serializer_generator.dart"
    builder_factories: [ "serializerGenerator" ]
    # The `partId` argument to `SharedPartBuilder` is "some_cool_builder"
    build_extensions: { ".dart": [ ".serializers.g.part" ] }
    auto_apply: dependents
    build_to: cache
    # To copy the `.g.part` content into `.g.dart` in the source tree
    applies_builders: [ "source_gen:combining_builder" ]