export default {
  index: 'Overview',
  'query-builder': 'QueryBuilder',
  'mutation-builder': 'MutationBuilder',
  'query-client': 'QueryClient',
  'query-state': 'QueryState',
  'query-options': 'QueryOptions',
  'infinite-queries': 'Infinite Queries',
  'dependent-queries': 'Dependent Queries',
  'parallel-queries': 'Parallel Queries',
  'prefetching': 'Prefetching',
  'offline-mutation-queue': 'Offline Mutation Queue',
  'cache-configuration': 'Cache Configuration',
  'cache-invalidation': 'Cache Invalidation',
  'error-handling': 'Error Handling',
  security: 'Security Features',
  advanced: 'Advanced Topics',
  'type-safety': 'Type Safety',
  examples: 'Examples',
}
