/// Entry point for the FASQ (Flutter Async State Query) package.
///
/// Exported APIs cover query/mutation primitives, caching, pagination,
/// performance tooling, persistence, and Flutter widgets for integrating
/// async data flows into applications.
library;

export 'src/cache/cache_config.dart';
export 'src/cache/cache_entry.dart';
export 'src/cache/cache_metrics.dart';
export 'src/cache/eviction/eviction_policy.dart';
export 'src/cache/hot_cache.dart';
export 'src/cache/query_cache.dart';
export 'src/circuit_breaker/circuit_breaker.dart';
export 'src/circuit_breaker/circuit_breaker_exceptions.dart';
export 'src/circuit_breaker/circuit_breaker_options.dart';
export 'src/circuit_breaker/circuit_breaker_registry.dart';
export 'src/circuit_breaker/circuit_open_callbacks.dart';
export 'src/circuit_breaker/circuit_open_event.dart';
export 'src/circuit_breaker/circuit_state.dart';
export 'src/circuit_breaker/circuit_stats.dart';
export 'src/client/query_client.dart';
export 'src/client/query_client_observer.dart';
export 'src/memory/memory_pressure_handler.dart';
export 'src/mutation/mutation.dart';
export 'src/mutation/mutation_meta.dart';
export 'src/mutation/mutation_options.dart';
export 'src/mutation/mutation_snapshot.dart';
export 'src/mutation/mutation_state.dart';
export 'src/mutation/mutation_status.dart';
export 'src/mutation/network_status.dart';
export 'src/mutation/offline_queue.dart';
export 'src/observability/error/error_context.dart';
export 'src/observability/error/error_reporter.dart';
export 'src/observability/logging/fasq_logger.dart';
export 'src/observability/performance/exporters/console_exporter.dart';
export 'src/observability/performance/exporters/json_exporter.dart';
export 'src/observability/performance/exporters/opentelemetry_exporter.dart';
export 'src/observability/performance/isolate_pool.dart';
export 'src/observability/performance/isolate_task.dart';
export 'src/observability/performance/metrics_config.dart';
export 'src/observability/performance/metrics_exporter.dart';
export 'src/observability/performance/performance_monitor.dart';
export 'src/observability/performance/throughput_metrics.dart';
export 'src/pagination/cursor_pagination.dart';
export 'src/pagination/page_number_pagination.dart';
export 'src/persistence/annotations.dart';
export 'src/persistence/cache_data_codec.dart';
export 'src/persistence/persistence_options.dart';
export 'src/query/cancellation/cancellation_token.dart';
export 'src/query/dependency/dependent.dart';
export 'src/query/dependency/query_dependency_manager.dart';
export 'src/query/infinite/infinite_query.dart';
export 'src/query/infinite/infinite_query_options.dart';
export 'src/query/infinite/infinite_query_state.dart';
export 'src/query/keys/query_key.dart';
export 'src/query/keys/typed_query_key.dart';
export 'src/query/prefetch/prefetch_config.dart';
export 'src/query/query.dart';
export 'src/query/query_meta.dart';
export 'src/query/query_options.dart';
export 'src/query/query_snapshot.dart';
export 'src/query/query_state.dart';
export 'src/query/query_status.dart';
export 'src/security/encryption_provider.dart';
export 'src/security/persistence_provider.dart';
export 'src/security/security_plugin.dart';
export 'src/security/security_provider.dart';
export 'src/widgets/mutation_builder.dart';
export 'src/widgets/query_builder.dart';
export 'src/widgets/query_client_provider.dart';
